name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v3
        with:
          project_id: multi-k8s-493910
          workload_identity_provider: projects/871393691181/locations/global/workloadIdentityPools/github-pool-multi-k8s/providers/gh-actions-provider-multi-k8s
          service_account: gh-actions-multi-k8s@multi-k8s-493910.iam.gserviceaccount.com

      - uses: google-github-actions/get-gke-credentials@v3
        with:
          cluster_name: autopilot-cluster-1
          location: us-central1
          project_id: multi-k8s-493910

      - name: Verify cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes